services:
  - type: web
    name: laravel-backend
    env: docker
    repo: https://github.com/BenjaminOrtiz05/Recuperativo-backend
    branch: main
    rootDir: .  # Cambia si Laravel está en una subcarpeta
    plan: free
    dockerContext: .
    dockerfilePath: ./Dockerfile
